### ISSUE TITLE
Database version 65

### ISSUE THREAD

**Issue by jonaslb** [GjjvdBurg/signal2html#1]
Hey,

I love your work, the dumped html looks very nice! It's the best "temporary" solution for people migrating Android-iOS where Signal doesn't yet provide a cross-backup solution, to look at their old messages.

Unfortunately I had to work with database version 65 instead of 23, which meant your scripts had a few errors.

I've made some very quick changes in a branch of my own, which means it now works with database version 65: https://github.com/jonaslb/signal2html

I took exactly zero care to make sure it was also still working with older versions though, so thats why I'm not sending you a PR. But please feel free to merge it anyway, if you like it, or to take parts of it if you want to do something differently.

**Comment by GjjvdBurg** [comment]
Hi @jonaslb,

Thanks for letting me know, glad to hear you managed to get it to work on your version! :tada: I don't have a database dump that uses version 65, so I won't be able to test your implementation. If you'd like to add your work to this repo I'd be happy to collaborate on a PR, judging by the changes you've made it wouldn't be too complicated.

(in any case, it's great to know at least one other person got use out of this! :smile:)

**Comment by 70nyIT** [comment]
@GjjvdBurg as of now I have database version 80 and it's not working with your code. Instead, I tested the fork of @jonaslb and it's working. I have Android, and I tested it both on Windows and Linux environments and it's working great. Hope you can merge the edits in your main tool!
One more suggestion: why not copying all the attachments in the output of your tool, and put local references to those files? Otherwise a user may loose the links to the files.

That said, I really loved what you did and it's an amazing useful tool for anyone like me that loves keeping backups of old conversations in a cross-compatible format. Html I think it's the natural best option 👏👏

**Comment by GjjvdBurg** [comment]
Hi @70nyIT and @jonaslb, I've now merged the edits by @jonaslb into the main package (see the PR #3). I've tried to make it backwards compatible to my original version and tested it to make sure it works on that. I'd appreciate it if either one of you could test the code in the PR branch to ensure that it works on your backups as well.

@70nyIT Copying the attachments to the output directory is a good idea, so that's coming in #4. Thanks for the positive feedback btw! :smile:

**Comment by 70nyIT** [comment]
hey @GjjvdBurg , thanks for your reply! I will take time today to test it and will report my tests results here 😉

**Comment by 70nyIT** [comment]
Tested and it's working properly ;)

**Comment by GjjvdBurg** [comment]
Great, thanks! Merged and released!
